### ISSUE TITLE
isTrulyEmpty({ prop: false}) returns true when invoked

### ISSUE THREAD

**Issue by akhader-mc** [benhutchins/dyngoose#445]
When a model property contains a single boolean entry: 

class SampleModel extends Dyngoose.Table {
{
  sample:  {
     prop: boolean
  }
}

Setting the following value on this model instance does not work: 

sampleModel.sample = { prop: false }

**Comment by benhutchins** [comment]
Thank you for the report @akhader-mc, this should now be resolved in Dyngoose `2.12.3`
