### ISSUE TITLE
Type Error when setting a connection on Table Metadata

### ISSUE THREAD

**Issue by akhader-mc** [benhutchins/dyngoose#454]
When setting a table metadata like below: 

(TableClass).schema.setMetadata(
{
  name: ....,
  connection: new Dyngoose.Connection.DynamoDBConnection({ ...} )
});

The following TS error is reported: 

TS2740: Type 'DynamoDBConnection' is missing the following properties from type 'DynamoDB': config, batchExecuteStatement, batchGetItem, batchWriteItem, and 54 more.  table.d.ts(17, 14): The expected type comes from property 'connection' which is declared here on type 'TableMetadata'

**Comment by benhutchins** [comment]
I'll test to confirm, but my guess is that you have a version of aws-ask that's out of sync with the one Dyngoose uses.

**Comment by akhader-mc** [comment]
The type on: https://github.com/benhutchins/dyngoose/blob/master/src/metadata/table.ts for the property 'connection' is DynamoDB rather than the interface Connection

**Comment by akhader-mc** [comment]
Using the "client" property on the connection solves the issue. Apologies for the misunderstanding

(TableClass).schema.setMetadata(
{
name: ....,
connection: new Dyngoose.Connection.DynamoDBConnection({ ...} ).client
})
