### ISSUE TITLE
How to use Custom Attribute Types

### ISSUE THREAD

**Issue by joshrathke** [benhutchins/dyngoose#476]
I have stumbled across the documentation relating to custom attributes and wondering how to actually apply them to a property within a Table model. Currently in the process of trying to implement a `version` field and would be more than happy to update the readme provided some course on how to move forward with custom attributes. Any way to set me off on the right path here?

```
import { Dyngoose } from 'dyngoose'
import { DynamoDB } from 'aws-sdk'

type Value = number
type Metadata = Dyngoose.Metadata.Attribute<number>

export class VersionAttributeType extends Dyngoose.AttributeType<Value, Metadata> {
  type = Dyngoose.DynamoAttributeType.Number

  getDefault() {
    return 0
  }

  toDynamo(value: Value): DynamoDB.AttributeValue {
    return { N: JSON.stringify(value + 1) }
  }
}
```

Reference to Attribute Docs: https://github.com/benhutchins/dyngoose/blob/master/docs/Attributes.md#custom-attribute-types

**Comment by benhutchins** [comment]
Auto-incrementing probably would not work out, but I will write out a better example and more documentation for custom attribute types. Thanks @joshrathke
