### ISSUE TITLE
Table.primaryKey.fromKey saving error - ExpressionAttributeNames must not be empty

### ISSUE THREAD

**Issue by jpmtrabbold** [benhutchins/dyngoose#481]
Hello! Just another minor nuisance I've encountered in this great library.

One pattern that I've been finding very useful is the primaryKey.fromKey. Here's how I'm using:
```typescript
const transaction = new Dyngoose.Transaction() 
// the following statement will always return an "entity" (whether it exists in the database or not)
const entity = UserTable.primaryKey.fromKey({id: '0001'})
// write the user's data
entity.name = "Name of the User"
// will only overwrite the fields that are actually assigned - very handy
if (hasAddress) {
   entity.address = "his/her address"
}
// ... (saves other stuff)
// "save" will intelligently create a new entity or update the existing one
transaction.save(entity)
```

So, this works perfectly. But, if I try to create an entity only using a primary key:
```typescript
const transaction = new Dyngoose.Transaction() 
const manyToManyEntity = UserRoleTable.primaryKey.fromKey({userId: '0001', roleId: '1231'})
if (isAdmin) { // in the example that causes the error, isAdmin is false
   manyToManyEntity.adminRoleId = "123123"
}
// do not write anything and save
transaction.save(manyToManyEntity)
```
And isAdmin === false, causing to not write any additional fields (other than the primary key ones), then it gives me the following error: `ExpressionAttributeNames must not be empty`.

It would nice to still be able to use `primaryKey.fromKey` even if I only want to create a very simple record with only the primary key fields.

**Comment by benhutchins** [comment]
I too find the `fromKey` method quite helpful. Especially when dealing with transactions or bulk operations. I'm glad to see Dyngoose is helpful to you. So to your issue…

Dyngoose tries to keep track of the "changed" fields, so when using `fromKey` it creates a new instance with the attributes for the keys and then resets the changes to empty.

By default, the `transaction.save` method is a helper utility. It mimics the `.save` method on the `Table` class. It looks at the current state and determines if the document was either newly created (usually using the `.new` method) or if the entire document is known (meaning the document was loaded from either the primary key, or an index that used full projection). If those are true, it feels it is best or safe to use a `PutItem` operation. In any other case, it uses an `UpdateItem` operation, where is only updates the selectively updated attributes. This is necessary when using indexes that do not have projection set to `ALL`, and it offers some (minimal) performance benefits. In the end, AWS charges you for number of Write Operations so it doesn't save cost, but it uploads less data which can be a good thing for larger documents.

In general, when `.fromKey` is used, Dyngoose considers that to be similar to when using an index without projection set to `ALL`. So when calling `.save`, it avoids using a `PutItem` to avoid deleting data unintentionally.

Well, you don't have to use `.save`. If you switch your call from `transaction.save(entity)` to `transaction.put(entity)` it will work.

**Comment by jpmtrabbold** [comment]
cool @benhutchins, thank you very much! Sure, so summarizing: if I'm only saving keys, I should use `put` directly. Got it.

Well, if at some point you manage to find a way of making this use case work with save(), it would definitely increase (even more) the DX for the library - less adoption friction. But I do understand the limitations when working with dynamodb, and after your explanation, I also think it's not doable. To minimize friction for newcomers, the library could handle those errors (like `ExpressionAttributeNames must not be empty`) and give a friendly message about possible misuses of your library that caused that error.

Thank you so much for the thorough explanation, really appreciate it!
