### ISSUE TITLE
maintenance state

### ISSUE THREAD

**Issue by iwpnd** [benhutchins/dyngoose#504]
Hi :wave:

I really like this library, as well as its documentation. I noticed a growing number of unmerged dependabot PRs and was wondering if you stopped its further development?

**Comment by benhutchins** [comment]
Still being marinated, only by me, and I just had a baby born so I haven’t had a much time recently. Any bugs that reported I’ve still been resolving but feature requests are on hold until the fall.

**Comment by iwpnd** [comment]
Congratulations 🍾 All the best!
