### ISSUE TITLE
autoscaling type error

### ISSUE THREAD

**Issue by jpmtrabbold** [benhutchins/dyngoose#544]
When defining a table with autoscaling, typescript is accusing this error:
![image](https://user-images.githubusercontent.com/16899648/139600555-38409856-1c69-434e-b3d3-704237545d65.png)

It's because it's forcing you to put the `read` and `write` attributes. No error here:
![image](https://user-images.githubusercontent.com/16899648/139600579-e9179a2d-801a-4882-b78b-fe1b647792c8.png)

The reason is the way `IThroughput` is written:

```ts
export interface IThroughput {
    read: number;
    write: number;
    autoScaling?: true | IThroughputAutoScalingCapacity | {
        read: IThroughputAutoScalingCapacity;
        write: IThroughputAutoScalingCapacity;
    };
}
```

A suggestion would be something like this:
```ts
interface IStaticThroughputFields {
    read: number;
    write: number;
}
interface IAutoScalingThroughputFields {
    autoScaling: true | IThroughputAutoScalingCapacity | {
        read: IThroughputAutoScalingCapacity;
        write: IThroughputAutoScalingCapacity;
    };
}

export type IThroughput = IStaticThroughputFields | IAutoScalingThroughputFields
```

**Comment by benhutchins** [comment]
This sounds like a great improvement. I'll add it with my next update.
