### ISSUE TITLE
Typescript disallows Primary key without sort key, example fails.

### ISSUE THREAD

**Issue by sblackstone** [benhutchins/dyngoose#569]
I'm attempting to define a table that has a primary key without a sort key.  The documentation has multiple examples of this working however, I'm getting a Typescript error:

```
 Generic type 'PrimaryKey<T, HashKeyType, RangeKeyType>' requires 3 type argument(s).
```

Any advice?

```
import { Dyngoose } from 'dyngoose'

@Dyngoose.$Table({ name: 'Tokens' })

class Token extends Dyngoose.Table {
  @Dyngoose.Attribute.String()
  public id: string

  @Dyngoose.$PrimaryKey('id')
  public static readonly primaryKey: Dyngoose.Query.PrimaryKey<Token, string>

  @Dyngoose.$DocumentClient()
  static readonly documentClient: Dyngoose.DocumentClient<Token>
}
```

**Comment by sblackstone** [comment]
I heard through the grapevine that 
```
 public static readonly primaryKey: Dyngoose.Query.PrimaryKey<Token, string, void>
```
 will do the trick.   So this may just be more of a documentation issue or Typescript version issue.

**Comment by benhutchins** [comment]
@sblackstone That's right, you need to explicitly use `void` for the type when you want no sort/range key. You cannot use undefined or it will have complaints.

If this isn't explicitly clear in the docs, I'll make it so.
