### ISSUE TITLE
AWS SDK v3

### ISSUE THREAD

**Issue by air2** [benhutchins/dyngoose#591]
Are there any plans to upgrade to AWS SDK v3?

**Comment by benhutchins** [comment]
I definitely will update to use AWS SDK v3 soon, within the next few months.

**Comment by iwpnd** [comment]
Hey @benhutchins, did you have a chance to assess the impact this has on dyngoose and the work necessary is to move it to v3? With a slight outline of the necessary steps and the "needs help" label, maybe we can get this out of the way, wdyt?

**Comment by benhutchins** [comment]
I have a functional branch converting to AWS v3 available at https://github.com/benhutchins/dyngoose/tree/feature/bh/upgrade-aws where I was working on a few other updates before releasing Dyngoose v4.0.0

**Comment by iwpnd** [comment]
Good to hear you're still working on it 🙏 please let me know if i can help in any shape or form

Do you think this can be released before EOL of aws-sdk-v2?

**Comment by iwpnd** [comment]
> Do you think this can be released before EOL of aws-sdk-v2?

re-reading this now, I didn't intend to make this sound as pushy as it does. Sorry, really appreciate your work. 🙏

**Comment by benhutchins** [comment]
Dyngoose v4.0.0 uses aws sdk v3.
