### ISSUE TITLE
undefined default values on .save()

### ISSUE THREAD

**Issue by iwpnd** [benhutchins/dyngoose#602]
Hi there @benhutchins  👋 

I stumbled face first in an issue that was driving me mad the entire afternoon.

```
import { Dyngoose } from 'dyngoose';
import { v4 as uuid } from 'uuid';

@Dyngoose.$Table({
    name: 'baguette',
})
export class BasicTable extends Dyngoose.Table {
    @Dyngoose.Attribute.String({ default: () => uuid() })
    public id: string;

    @Dyngoose.Attribute.String()
    public otherId: string;

    @Dyngoose.Attribute.Date({ nowOnCreate: true })
    public createdAt: string;

    @Dyngoose.Attribute.Date({ nowOnUpdate: true })
    public updatedAt: string;

    @Dyngoose.$PrimaryKey('id')
    static readonly pkId: Dyngoose.Query.PrimaryKey<BasicTable, string, string>;
}
```

So say on a `POST /baguette` I want to create an entry, and the only field that I send is `otherId`. So in my test I send it, and it returns a 201 with the expected payload.

```
 {
      id: '7a71f331-c12b-4c3d-a4e4-207bcc367b18',
      otherId: '980296e7-422f-4026-845b-2a0217242cc7',
      createdAt: '2022-08-22T18:51:23.118Z',
      updatedAt: '2022-08-22T18:51:23.197Z'
    }
```

Now I want to test the update of the entry `PUT /baguette/:id`, and create it in my test, before I test my put endpoint.

```
const data = {
      otherId: '980296e7-422f-4026-845b-2a0217242cc7',
      id: undefined,
      createdAt: undefined,
      updatedAt: undefined
}
const baguette = BaseTable.new(data)
await baguette.save()
console.log(baguette.toJSON())
```

Expectation:
```
 {
      id: '7a71f331-c12b-4c3d-a4e4-207bcc367b18',
      otherId: '980296e7-422f-4026-845b-2a0217242cc7',
      createdAt: '2022-08-22T18:51:23.118Z',
      updatedAt: '2022-08-22T18:51:23.197Z'
    }
```

Reality:
```
ValidationException: One of the required keys was not given a value
```

If I pass the `id`, because it's the pk, it creates a new row, but without populating the `createdAt` and `updatedAt` column.

What works is:
```
const baguette = BaseTable.new({ otherId: '980296e7-422f-4026-845b-2a0217242cc7' })
await baguette.save()
console.log(baguette.toJSON())
> {
      id: '7a71f331-c12b-4c3d-a4e4-207bcc367b18',
      otherId: '980296e7-422f-4026-845b-2a0217242cc7',
      createdAt: '2022-08-22T18:51:23.118Z',
      updatedAt: '2022-08-22T18:51:23.197Z'
    }
```

Is this intentional, or did I miss something about `undefined` in js/ts? :S

**Comment by benhutchins** [comment]
This isn't truly intentional. This is happening because the order of operations that exist currently are:

1. You call `.new()`
2. It goes through attributes and generates default values as necessary.
3. It applies the values you provided in the `.new(values)`
4. Calling `.set('property', undefined)` which does intentionally clear the value.

A fix will be coming in the next release.
