### ISSUE TITLE
List attribute type - Feature request

### ISSUE THREAD

**Issue by kulovan** [benhutchins/dyngoose#608]
Hello 👋🏻 ,

I migrated to this super lib from the plain `aws-sdk`, but I have a problem mapping existing database entries.
I have a field that is an array of objects and it would be very useful if the list attribute type would also exist.

Are you planning to implement this feature? If yes, when do you plan to release it?
Do you have any suggestions other than using the `Attribute.Any()` type? In that case I would have to implement logic that makes the ODM backwards compatible with the previous entries.

Many thanks for you support in advance!

**Comment by KevinToala** [comment]
In our project we managed to support list type attributes with a custom attribute

```
import { Dyngoose, Table } from "dyngoose";
import DynamoDB from "aws-sdk/clients/dynamodb";

type Value = Array<unknown>;
type Metadata = Dyngoose.Metadata.Attribute<Array<unknown>>;

class ListAttributeType extends Dyngoose.AttributeType<Value, Metadata> {
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
  type = "L";

  toDynamo(value: Value): DynamoDB.AttributeValue {
    return DynamoDB.Converter.marshall({ value }).value;
  }

  fromDynamo(value: DynamoDB.AttributeValue): Value | null {
    return DynamoDB.Converter.unmarshall({ value }).value;
  }
}

interface AttributeDefinition {
  (record: Table, propertyName: string): void;
  getAttribute: (record: Table, propertyName: string) => unknown;
}

export function ListAttribute(metadata?: Metadata): AttributeDefinition {
  const define = function (record: Table, propertyName: string): void {
    const decorator = new ListAttributeType(record, propertyName, metadata);
    decorator.decorate();
  };

  define.getAttribute = function (
    record: Table,
    propertyName: string
  ): unknown {
    const decorator = new ListAttributeType(record, propertyName, metadata);
    return decorator.attribute;
  };

  return define;
}


class Store {
  // code...
  @ListAttribute({ name: "stFilters" })
  filters?: string[];
  // code...
}
```

For what we require it is enough, most likely it can be improved but it helps us until we have native support from the library

**Comment by KevinToala** [comment]
It took us a while to find a way to use a custom attribute, maybe it's not the right way but it worked for us. I think the documentation needs to be improved @benhutchins

**Comment by kulovan** [comment]
Cool, thanks @KevinToala for clarifying!
