### ISSUE TITLE
Is this lib active?

### ISSUE THREAD

**Issue by luisdemarchi** [benhutchins/dyngoose#614]
@benhutchins  I see several issues unanswered or answered by other members. Also some PRs stopped. I want to put in a new project, I would not like to put something discounted

**Comment by benhutchins** [comment]
@luisdemarchi This is definitely still active and being maintained. Open PRs are for some maintenance upgrades, except for one which isn't suitable to be merged without some revisions.

**Comment by KevinToala** [comment]
What good news, in our company we started using it as part of an update in our new architecture and we are a little worried that the project will not continue active. We see that it is a simple library to implement, strongly typed with typescript and it helps us to have a simpler and cleaner code.
