### ISSUE TITLE
Any support for AWS CDK?

### ISSUE THREAD

**Issue by pjvds** [benhutchins/dyngoose#626]
We define our stack with the AWS Cloud Development Kit and want to migrate our DynamoDB code to use dyngoose. Is are way to create a [dynamodb.Table](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-dynamodb.Table.html) from a dyngoose table definition?

**Comment by benhutchins** [comment]
This is a great feature request, will certainly add an official adapter to the library.

**Comment by benhutchins** [comment]
I’ve added CDK utilities to Dyngoose v4.0.0

**Comment by pjvds** [comment]
Love the fast turn over time. You rock!
