### ISSUE TITLE
Missing properties for data that has Any attribute

### ISSUE THREAD

**Issue by jcjp** [benhutchins/dyngoose#628]
I have a endpoint where I request using GET and use a library (https://github.com/Melchyore/adonis-dynamodb) on top of this Dyngoose to query on our DynamoDB using the model stated above.

Here is a code snippet of the DynamoDB query / get:

```JavaScript
public async items({request, response}: HttpContextContract) {
  const records = await DynamoDb.gsi_id_class.query({
    pid: request.id,
    class: this.class
  })
  response.ok({
    records,
  })
}
```

Here is my DynamoDB model:

```JavaScript
...
@DynamoDB.$Table({name: Env.get('TABLE', '')})
export default class DynamoDb extends DynamoDB.Table {
  ...

    @DynamoDB.Attribute.String()
    public name: string

    @DynamoDB.Attribute.String()
    public description: string

    @DynamoDB.Attribute.String()
    public sample: string

    @DynamoDB.Attribute.Any()
    public type: string | number

    @DynamoDB.Attribute.Any()
    public order: string | number

    @DynamoDB.Attribute.Any()
    public sample: string

    @DynamoDB.Attribute.Any() // Even tried StringSet but doesn't work
    public values: Array<string>
  ....
}
```

It returns the items, however they are missing properties from the DynamoDB model / structure. Here is a sample return from DynamoDB query:

```JavaScript
DynamoDb {
  __attributes: {
    description: {
      S: 'Test description.'
    },
    createdAt: { N: '1674708730' },
    class: { S: 'node' },
    sample: {
      S: 'Test sample'
    },
    updatedAt: { N: '1674708730' },
    pid: { S: '0' },
    name: { S: 'Test name' },
    type: { N: '1' },
    values: { L: [Array] },
    id: { S: 'Test id' },
    timestamp: { N: '1674708730' },
    order: { S: 'Unspecified' }
  },
  __original: {},
  __updatedAttributes: [],
  __removedAttributes: [],
  __updateOperators: {},
  __putRequired: false,
  __entireDocumentIsKnown: false
}
```

Here is a sample result of toJSON of that DynamoDB output query above:

```JavaScript
{
  "id": "Test id",
  "pid": "0",
  "timestamp": 1674708730,
  "class": "node",
  "createdAt": 1674708730,,
  "updatedAt": 1674708730,
  "name": "Test name",
  "description": "Test description",
  "version": 1
}
```

Not sure but when using `.Any()` attribute it actually omits some properties which are missing on the toJSON function, when I use the library to create data to the database it queries the data correctly even it using the `.Any()` attribute. I created some data properties on the database directly to test the data without needing to go into our process however when querying data that where directly created it doesn't get returned back as properties.

This is also somehow related to the `L` attribute above we have `values: { L: [Array] }`.

**Comment by benhutchins** [comment]
The `Any` type stores values formatted using JSON in a String attribute. It does not look any value. I do plan to add a new attribute type to add support for any value, which will rely on AWS's marshall utilities, in a future release.

**Comment by benhutchins** [comment]
I have added support for Dynamic attributes using AWS's marshall utility, [see the docs](https://github.com/benhutchins/dyngoose/blob/master/docs/Attributes.md#dyngoose-attribute-types).
