### ISSUE TITLE
Is there option to save unknown columns with batchPut?

### ISSUE THREAD

**Issue by michalkotowski1** [benhutchins/dyngoose#638]
Im saving records with hundreds of fields, sometimes there are fields that are not specified in definition, and I also needs to save them.

Is there a way to save document with fields which were not specified in table definition (sth like dynamoose saveUnknown).

BTW, great job with this lib/api def/doc!

**Comment by benhutchins** [comment]
There isn't support for saving unknown columns yet, but I do plan to add that in a future release.

**Comment by benhutchins** [comment]
The List attributes and Map attributes now support saving unknown columns, as part of Dyngoose 4.1.0. The table-level support should be coming out in the next release, Dyngoose 4.2.0.

**Comment by benhutchins** [comment]
I have added support for Dynamic attributes using AWS's marshall utility, [see the docs](https://github.com/benhutchins/dyngoose/blob/master/docs/Attributes.md#dyngoose-attribute-types).
