### ISSUE TITLE
Move from amazon-dax-client to @aws-sdk/client-dax

### ISSUE THREAD

**Issue by air2** [benhutchins/dyngoose#644]
Hello, thank you for solving #591 !! I can now get rid of a lot of v2 code in my codebase. However I noticed aws-sdk v2 is still included in the dependencies, because of amazon-dax, there is @aws-sdk/client-dax. I am totally **NOT** familiar with those packages. So I really do not know how much effort it is to move to the v3 lib, but if you could that would get rid of the aws-sdk v2 lib completely.

**Comment by benhutchins** [comment]
Looks like DAX is not yet supported by aws-sdk v3, so I have to drop support for DAX from Dyngoose until that support is created.
