### ISSUE TITLE
Working with date using Dyngoose

### ISSUE THREAD

**Issue by victuk** [benhutchins/dyngoose#654]
How do i use Dyngoose to get records based on the date saved on it using "new Date()"

e.g if i want to query a collection for records that was generated today, how do i write it?

await //Collection Name//.search({createdAt: //what can i write here to get records generated for the current day//});

**Comment by benhutchins** [comment]
You can do something like this:

```typescript
const startOfDay = new Date()
startOfDay.setUTCHours(0, 0, 0, 0)
const endOfDay = new Date()
endOfDay.setUTCHours(23, 59, 59, 999)

const results = await Collection.primaryKeyOrIndex.search()
  .filter('createdAt').between(startOfDay, endOfDay)
  .exec()
```

Some notes:

1. All dates are always stored in UTC.
2. You can use a query rather than a MagicSearch instance
3. It's easier to work with dates using a Date library, like dayjs.
