### ISSUE TITLE
@aws-sdk/client-dynamodb dependency

### ISSUE THREAD

**Issue by iwpnd** [benhutchins/dyngoose#659]
Hi @benhutchins 

`@aws-sdk/client-dynamodb` appears to be a hard dependency and is missing? 

If I do not specifically add it to my project I get a bunch of errors:

```
Error: Cannot find module '@aws-sdk/client-dynamodb'
```

Is there anything else I need to consider moving from v3 to > v4?

**Comment by benhutchins** [comment]
`@aws-sdk/client-dynamodb` is listed as a peer dependency. The intention is to use the existing version of `@aws-sdk/client-dynamodb` from your library, that way it allows you to handle upgrade and using the client consistently outside of Dyngoose. Previously, `aws-sdk` was a peer dependency but almost everyone had that installed.

I should likely add a note to the upgrade guide and installation guide for Dyngoose about this. Thank you for the report @iwpnd

**Comment by iwpnd** [comment]
Understood, thank you for the quick response
