### ISSUE TITLE
Support for AbortController

### ISSUE THREAD

**Issue by air2** [benhutchins/dyngoose#670]
Hii, I was wondering of there are any plans to support AbortController/AbortSignal, to abort query's and calls to dynamodb. The aws-sdk/client-* support AbortSignal and it would be nice if this would also be supported in this wrapper package.

**Comment by air2** [comment]
I added pull request #671 which implemented this feature for get request, could you please let me know what you think? It is just an example from how I think this could be implemented, but maybe you have a complete different idea about this.

**Comment by benhutchins** [comment]
Closing this issue as the enhancement has been implemented. Thank you again @air2
