### ISSUE TITLE
Q: How do you handle a model of an existing table with a variable JSON object

### ISSUE THREAD

**Issue by ktwbc** [benhutchins/dyngoose#676]
I have an existing table which was used with dynamo-types, and I'm upgrading to Dyngoose. In my previous model file had one field "contents" which was a JSON object that was highly variable, which is one of the points of schemaless dynamodb. In dynamo-types it was simply defined as "object", and it was saved as a Map in ddb itself (i.e. not JSON stringified).

I have my model for Dyngoose built but now have an issue. I can't use .Attributes.Map() because that requires me to spec out the whole JSON object and the schema varies wildly, so that's not practical. If I use Attributes.Any() then when I load the record and try to use the contents field, it's undefined because Dyngoose is expecting stringified JSON which it's not, and therefore it doesn't show a value.

How can I use Dyngoose with this existing table? It's not possible to go back and stringify all that JSON and quite frankly I wouldn't want to because it makes it harder to view the data with a ddb client viewer.

**Comment by benhutchins** [comment]
Try without any type, just `@Dyngoose.Attribute`. That will use the object serialization utilities from AWS (marshal), rather than JSON stringification. It doesn't handle complex types well, but it works well for generic types.

**Comment by benhutchins** [comment]
If you want to pass options to the marshall utility, you can do so by using the Dynamic attribute:

`@Dyngoose.Attribute.Dynamic(...)`

Dynamic is the default attribute type when you call `@Dyngoose.Attribute()` without specifying a type as well.

Hopefully, this helps with the existing data and is generally a better default than using the `.Any()` attribute. I do wish I had called the Any attribute Json but haven't wanted to force a rename on users.

**Comment by ktwbc** [comment]
ok that worked, thank you
