### ISSUE TITLE
Can't configure connection props

### ISSUE THREAD

**Issue by byeze** [benhutchins/dyngoose#680]
Hello! I'm getting this error when configuring connection properties for DynamoDb.
I'm following the example described on https://github.com/benhutchins/dyngoose/blob/master/docs/Connections.md#global

<img width="795" alt="image" src="https://github.com/benhutchins/dyngoose/assets/7424138/1af37b80-096e-4eb7-8fd1-230558ab1821">

I've tried using the exact example on the wiki, but the error changes to: "Property 'defaultConnection' does not exists on..."

**Comment by benhutchins** [comment]
@byeze I've confirmed this is not working as expected and the docs were out of date. I've updated this, fix will be included in `dyngoose@4.11.1`

**Comment by byeze** [comment]
Thank you!
