### ISSUE TITLE
Possible Bug: Conditions Ignored in update function

### ISSUE THREAD

**Issue by MichaelF92** [benhutchins/dyngoose#699]
I have the code like the following:

try {
  await DynamoTable.primaryKey.update({
    hash: id,
    range: meta_id,
    changes: { status: newStatus },
    conditions: { status: 'pending' }
  });
} catch (error) {
    if (error.name === 'ConditionalCheckFailedException') {
      return 404;
    }
    return 500;
}

return 200;
During unit testing, no matter what I change the mock data for the test record to, and no matter what I change the condition to (using different attributes, different values for the status attribute). The unit tests always returns a 200 response, instead of an expected 404 on the condition being not met.

However, using the following code:

try {
  const item = DynamoTable.primaryKey.fromKey(id, meta_id);
  item.fromJSON({
    ...item.toJSON(),
    ...{ status: newStatus }
  });
  await item.save({ conditions: { status: 'pending' } });
} catch (error) {
    if (error.name === 'ConditionalCheckFailedException') {
      return 404;
    }
    return 500;
}

return 200;

Does return 404 and other values as expected during testing.

This is happening anywhere where conditions are used in an update function in my code. It appears the update function is ignoring the conditions passed to it. Is there a special behavior with update I am overlooking?

Thank you for your help.

**Comment by benhutchins** [comment]
Definitely a bug. Fixed this and pushed a new build, 4.11.2 should be available shortly.

**Comment by benhutchins** [comment]
I try to keep strict typing, but sometimes simple things can be missed. I'll work to expand unit test coverage with the `PrimaryKey.update` method as part of the work I am doing for #692. For now, I believe I found the problem causing conditions to be ignored.

**Comment by MichaelF92** [comment]
Brilliant. Thank you for the prompt response and fix.
